### ISSUE TITLE
Ganti emailnya :')

### ISSUE THREAD

**Issue by kikuKeii** [ariframadhan01/ariframadhan01.github.io#1]
# Selamat Malam kepada @ariframadhan01 
Gan saya gak masalah kok mau copy paste,.. tapi email saya diganti dong sama email sendiri, Kalo gak di ganti kalo lu ngelamar... emailnya masuk ke saya :"

> Lain kali lebih fokus gan :" 

ini masih email saya
https://github.com/ariframadhan01/ariframadhan01.github.io/blob/6de6b8b290fe97fa6ab4fe11f3564264a59bc7b8/index.html#L481

![qwesd](https://user-images.githubusercontent.com/60594222/87055833-0a488e00-c22f-11ea-9419-b65b8fb02fad.png)

# Sekian dan terimaksi

**Comment by TioA** [comment]
Sudah solved sepertinya

**Comment by ariframadhan01** [comment]
Maaf gan saya hanya copy paste dan belum meminta izin kepada pembuat. Cv
ini hanya untuk show off ke temen doang. Sekali lagi saya minta maaaf.

Pada tanggal Jum, 10 Jul 2020 pukul 07.16 TioA <notifications@github.com>
menulis:

**Comment by kikuKeii** [comment]
No problem gan yang penting mau belajar
